prod_snowflake_account   = "cm17072.south-central-us.azure"
prod_snowflake_username  = "SRUTHIMANI173"
prod_snowflake_password  = "Sachinindia123*"
prod_snowflake_role      = "ACCOUNTADMIN"
prod_snowflake_warehouse = "COMPUTE_WH2"

dev_snowflake_account   = "cm17072.south-central-us.azure"
dev_snowflake_username  = "SRUTHIMANI173"
dev_snowflake_password  = "Sachinindia123*"
dev_snowflake_role      = "ACCOUNTADMIN"
dev_snowflake_warehouse = "DEV_COMPUTE_WH2"
dev_snowflake_warehouse_TEST = "DEV_COMPUTE_WH_TEST"
