name: Run SQL Files

on:
  push:
    branches:
      - stage
    paths:
      - 'sql/**.sql'  # Only trigger on SQL files in sql directory

jobs:
  execute-sql:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"  # Skip if commit message contains [skip ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python pytz

      - name: Run SQL files
        run: python run_ddls.py