name: Run Python on Merge

on:
  push:
    branches:
      - stage  # triggers on merge to stage branch

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: AWS_ACCESS_KEY_ID1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or 3.10, etc.

      - name: Run test.py
        run: python test.py
