name: Run Snowflake DDLs via Python

on:
  push:
    branches:
      - stage

jobs:
  snowflake-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Added for pushing archive commits

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install snowflake-connector-python
          pip install pytz

      - name: Configure Git
        run: |
          git config --global user.name "Sabarirepository"
          git config --global user.email "sabarirepository@users.noreply.github.com"

      - name: Run SQL Scripts
        run: python run_ddls.py